#' Fetch and Install R Client Functions from a Remote API
#'
#' This function downloads R client source code from the \code{client_fns} endpoint of remote API services (typically Plumber servers). The downloaded code is parsed and evaluated into the specified environment, making client helper functions immediately available in R. The \code{client_fns} endpoint should serve plain R code, with an appropriate `Content-Type` header (e.g., `text/plain`). Optionally, if the endpoint serves JSON, this function will attempt to extract the code from the \code{$code} field. If an API key is required, it will be sent as a bearer token.
#'
#' @param base_url Character. The root URL of the API (without trailing slash). Required.
#' @param path Character. The path to the client code endpoint. Defaults to \code{"client_fns"}.
#' @param token Character. Optional API authentication token. Defaults to the value of \code{Sys.getenv("ChatRBox_TOKEN")}), retrieved from the global environment. This default is also true for the \code{token} argument in \code{\link{build_api_client}} (which is the equivalent to this function for OpenAPI JSON schemas rather than base URLs) since these are the helpers that extract client functions for a single API input. These functions are later iterated over input lists so that users may upload multiple API services simultaneously. 
#' @param auth_scheme Character. API authorization scheme. Defaults to NULL, given \code{token_header} is populated. The user-facing R6 object \code{\link{ChatRBox}} only contains the \code{token_header} argument but users may choose authorization methods via \code{auth_scheme} by modifying this function.
#' @param token_header Character. API token header name if \code{auth_scheme} is \code{NULL}. Defaults to "X-API-Key".
#' @param timeout Numeric. Timeout value. Defaults to 60 seconds.
#' @param method Character. API HTTP method. Defaults to "GET" for likely chatbot API services.
#' @param verbose Logical. Whether to print verbose information. Defaults to \code{FALSE}. 
#' @param client_envir Environment. The environment in which to evaluate (and store) the loaded client functions. Defaults to \code{new.env()}.
#'
#' @return The environment (\code{client_envir}) containing the evaluated client functions.
#' @details
#' This function uses the helper function \code{\link{make_req}} and acts as a helper function to \code{\link{get_api_client_env}}. This function extracts client function R source code from the \code{client_fns} endpoint of an API service. These are downloaded such that they are available for user and chatbot use in R. Therefore, this function is specific to API services provided as API URLs via \code{services_list}, as it is assumed that these contain client function code, compared to those provided as OpenAPI JSON schema URLs via \code{openapi_list} which are not assumed to contain the \code{client_fns} endpoint. When APIs are provided via \code{openapi_list} instead, client functions are automatically generated by ChatRBox and collated with the client functions extracted from \code{services_list} APIs. Hence, chatbots view all API services equally and choose the most appropriate service path to fulfil user requests from the collated list.   
#' @importFrom httr2 req_perform resp_status_desc resp_content_type resp_body_string resp_is_error resp_body_json
#' @importFrom stringr str_detect
#' @seealso \code{\link{make_req}}, \code{\link{get_api_client_env}}
#' @example man/examples/examples_api_service.R
#' @export
get_api_client_fns <- function(
    base_url,
    path = "client_fns",
    token = Sys.getenv("ChatRBox_TOKEN", NA),
    auth_scheme = NULL,
    token_header = "X-API-Key",
    timeout = 60,
    method = "GET",
    verbose = FALSE,
    client_envir = new.env()
) {
  if (is.null(base_url)) stop("base_url must be provided.")
  
  # Build request using centralized helper
  # Remaining arguments take default helper function values
  req <- make_req(
    base_url = base_url,
    path = path,
    token = token,
    auth_scheme = auth_scheme,
    token_header = token_header,  
    timeout = timeout,
    method = method,
    verbose = verbose   
  )
  
  # Perform request
  resp <- httr2::req_perform(req)
  
  # Error if request failed
  if (httr2::resp_is_error(resp)) {
    stop("API request failed: ", httr2::resp_status_desc(resp))
  }
  
  # Parse content
  content_type <- httr2::resp_content_type(resp)
  if (stringr::str_detect(content_type, "text")) {
    content_txt <- httr2::resp_body_string(resp)
  } else if (stringr::str_detect(content_type, "json")) {
    content_json <- httr2::resp_body_json(resp)
    content_txt <- if (!is.null(content_json$code)) content_json$code else content_json
  } else {
    stop("Unsupported Content-Type: ", content_type)
  }
  
  # Evaluate code in provided environment
  eval(parse(text = content_txt), envir = client_envir)
  invisible(client_envir)
}

#' Generates Client Function Environments for a List of API Service URLs
#'
#' This function iterates over a named list of API service URLs, extracting R client functions for each from the \code{client_fns} API endpoint using \code{\link{get_api_client_fns}}. These are returned as a named list of environments. Authentication tokens and custom headers are assigned to specific services through named lists, if required to access protected APIs.
#' @param services_list List. Named list of API service base URLs as character strings, without trailing slashes. Required.
#' @param token_service List. Named list of API authentication tokens, with names matching APIs in \code{services_list}. Each token is used only for the matching service via pair matching. Error messages will throw for mismatched, duplicated and missing names. Defaults to empty list.
#' @param header_service List. Named list of authorization header names for each token. Each header is used only for the matching service via pair matching. Error messages will throw for mismatched, duplicated and missing names. Defaults to empty list. Users may dictate authorization method using this argument within the \code{\link{ChatRBox}} R6 object or edit the source code in \code{\link{get_api_client_fns}} which includes the \code{auth_scheme} argument. 
#' @param ... Additional arguments passed to \code{\link{get_api_client_fns}}.
#'
#' @return
#' A named list of environments, one for each service in \code{services_list}, where each environment contains the generated client functions for that service. Names correspond to those inputted in \code{services_list}. This nested environment structure prevents namespace conflict, especially for multiple external API services.
#'
#' @details
#' This function applies \code{\link{get_api_client_fns}} to every API service URL in \code{services_list} in order to extract the client functions for each endpoint, for chatbot access. It is assumed that these API services have the endpoint \code{client_fns} containing client functions as R source code. These functions also enable the use of tokens and token headers to access protected APIs, whereby tokens may be entered as character strings or environment variables. This function and \code{\link{get_api_client_fns}} have equivalent functions called \code{\link{build_api_client_env}} and \code{\link{build_api_client}} for when the \code{client_fns} endpoint is not present. These rather generate client function R source code for each endpoint in an OpenAPI JSON schema and can also be utilized with access tokens. Notably, separate token and token header lists are required for APIs loaded as service URLs or OpenAPI JSON schemas, and schemas must be provided via the \code{openapi_list} rather than \code{services_list} argument upon chatbot initialization.    
#' @seealso \code{\link{get_api_client_fns}}, \code{\link{build_api_client_env}}, \code{\link{build_api_client}}  
#' @example man/examples/examples_api_service.R
#' @export
get_api_client_env <- function(
    services_list,
    token_service = list(),
    header_service = list(),
    ...) {
  
  # Returns empty list when services_list is empty
  if (length(services_list) == 0) return(list())
  
  # Extracts names for optional token matching
  nm <- names(services_list)
  if (is.null(nm)) stop("services_list must be a named list/vector.")
  
  # Helper function checks that names are present in token list
  check_names(token_service, "token_service", "services_list")
  check_names(header_service, "header_service", "services_list")
  
  # Helper function checks that token list names have matching service
  validate_name_match(token_service, services_list, "token_service", "services_list")
  validate_name_match(header_service, services_list, "header_service", "services_list")
  
  # Helper function checks that token list names are not duplicated 
  check_duplicate_names(token_service, "token_service")
  check_duplicate_names(header_service, "header_service")
  
  env_list <- mapply(
    FUN = function(service_url, service_name) {
      token <- if (!is.null(token_service) && !is.null(names(token_service)) && service_name %in% names(token_service))
        token_service[[service_name]] else NULL
      header <- if (!is.null(header_service) && !is.null(names(header_service)) && service_name %in% names(header_service))
        header_service[[service_name]] else "X-API-Key"
      get_api_client_fns(
        base_url = service_url,
        token = if (is.null(token) || is.na(token)) NULL else token,
        token_header = if (is.null(header) || is.na(header)) "X-API-Key" else header,
        ...
      )
    },
    service_url = services_list,
    service_name = nm,
    SIMPLIFY = FALSE, USE.NAMES = TRUE
  )
  return(env_list)
}
